const WIDTH = 800;
const HEIGHT = 600;

const GRAVITATION = 0.88;
const BLOBBY_JUMP_BUFFER = GRAVITATION / 2;
const BALL_GRAVITATION = 0.28;
const BALL_RADIUS = 31.5;
const BALL_COLLISION_VELOCITY = 13.125;
const STANDARD_BALL_HEIGHT = 269 + BALL_RADIUS;

const BLOBBY_HEIGHT = 89;
const BLOBBY_JUMP_ACCELERATION = 15.1;
const BLOBBY_SPEED = 4.5;
const BLOBBY_UPPER_SPHERE = 19;
const BLOBBY_UPPER_RADIUS = 25;
const BLOBBY_LOWER_SPHERE = 13;
const BLOBBY_LOWER_RADIUS = 33;

const GROUND_PLANE_HEIGHT_MAX = 500;
const GROUND_PLANE_HEIGHT = GROUND_PLANE_HEIGHT_MAX - BLOBBY_HEIGHT / 2;

const NET_POSITION_X = 400;
const NET_SPHERE_POSITION = 284;
const NET_RADIUS = 7;

module.exports = {
  WIDTH,
  HEIGHT,

  GRAVITATION,
  BLOBBY_JUMP_BUFFER,
  BALL_GRAVITATION,
  BALL_RADIUS,
  BALL_COLLISION_VELOCITY,
  STANDARD_BALL_HEIGHT,

  BLOBBY_HEIGHT,
  BLOBBY_JUMP_ACCELERATION,
  BLOBBY_SPEED,
  BLOBBY_UPPER_SPHERE,
  BLOBBY_UPPER_RADIUS,
  BLOBBY_LOWER_SPHERE,
  BLOBBY_LOWER_RADIUS,

  GROUND_PLANE_HEIGHT_MAX,
  GROUND_PLANE_HEIGHT,

  NET_POSITION_X,
  NET_SPHERE_POSITION,
  NET_RADIUS
};
